fix: error when removing v2ctl for v5
v2ctl has been removed since v5, so the script will fail during removing.

```
rm: cannot remove '/usr/local/bin/v2ctl': No such file or directory
error: Failed to remove V2Ray.
```